# Generated by Django 5.0.7 on 2024-08-31 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_remove_link_summary_link_created_at_link_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='user_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
