# Generated by Django 5.0.7 on 2024-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_alter_link_url_link_unique_user_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="category",
            field=models.CharField(default="ALL", max_length=255),
        ),
    ]
