# Generated by Django 5.0.7 on 2024-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_link_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(default="제목이 없다KHU", max_length=255),
        ),
    ]
