# Generated by Django 5.0.7 on 2024-11-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_link_description_alter_link_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(default="No Title", max_length=255),
        ),
    ]
